#!/data/data/com.termux/files/usr/bin/bash

# Author:  MrAlpha786   (github.com/MrAlpha786)

#colors and other variables.
R='\033[1;31m'
C='\033[0;36m'
B='\033[1;34m'
G='\033[1;32m'
Y='\033[1;33m'
U='\033[3A'
FILE=$(which login)
LOCK="$PREFIX/bin/applets/lockscr"


#Banner
banner () {
    clear
    echo
    echo -e $B" ┌─────────────────────────┐ "
    echo -e $B" │$C      TERMUX LOGIN       $B│"
    echo -e $B" └─────────────────────────┘ "
    echo -e $R"  -> MrAlpha786 "
    echo
    echo
}



#Check if lock already exists.
grep -q "export VAL" $FILE; 

#if true then remove lock
if [ $? -eq 0 ]; then
    banner
    echo -en $Y" [*] Removing Lock......................\r"
    sleep 1
    rm -f $LOCK
    sed -i '/VAL=/d' $FILE
    sed -i '/export VAL/d' $FILE
    echo -e $Y" [!] Removing Lock......................$G DONE"
    echo

#if lock do not exist. set one
else

    curl https://raw.githubusercontent.com/MrAlpha786/termux-login-password/master/lock-script > $LOCK
    banner
    echo -en $Y" [*] Setting Lock.......................\r"
    sleep 1.5
    bash $LOCK set_Pass
    err=$?

    banner
    echo -en $Y" [*] Setting Lock.......................\r"
    #if true set lock
    if [ $err -eq 0 ]; then

        sed -i "3 a export VAL; bash $LOCK; [ \$? -ne 0 ] && exit; unset VAL;" $FILE
        sleep 1.5
        echo -e $Y" [!] Setting Lock.......................$G DONE"
        echo

    #else skip setup and exit
    else
        rm -f $LOCK
        echo -e $Y" [!] Setting Lock.......................$R ERR"
        echo
        echo -e $R" [!] Exiting...                               "
        exit
    fi
fi

