#!/data/data/com.termux/files/usr/bin/bash


#colors and other variables.
R='\033[1;31m'
C='\033[0;36m'
B='\033[1;34m'
G='\033[1;32m'
Y='\033[1;33m'
FILE=/data/data/com.termux/files/usr/bin/login

lock () {
}

#Banner
banner () {
    clear
    echo
    echo -e $B" ┌─────────────────────────┐ "
    echo -e $B" │$C     TERMUX LOGIN         $B│"
    echo -e $B" └─────────────────────────┘ "
    echo -e $R"  -> MrAlpha786 "
    echo
    echo
}

banner
echo -e $Y" [*] Setting Lock.......................\r"
lock
export VAL=$PREFIX/share/val
bash$PREFIX/etc/lockscr
err=$?
unset VAL
banner
echo -e $Y" [*] Setting Lock.......................\r"

if [ ${err} -eq 0 ]; then
    sed -i '2 a export VAL=$PREFIX/share/val; bash $PREFIX/etc/lockscr; [ $? -ne 0 ] && exit; unset VAL;' $FILE
    sleep 2
    echo -e $Y" [!] Setting Lock.......................$G DONE"
    echo

#else skip setup and exit
else
    rm -rf $PREFIX/etc/lockscr
    echo -e $Y" [!] Setting Lock.......................$R ERR"
    echo
    echo -e $R" [!] Exiting...                               "
    exit
fi

